export const ADD_LOGIN = "ADD_LOGIN"
export const ADD_DATA_ACCOUNT = "ADD_DATA_ACCOUNT"
export const DEL_LOGIN = "DEL_LOGIN"
export const GET_LOGIN = "GET_LOGIN"
export const UPDATE_BALANCE = "UPDATE_BALANCE"