export { default as Main } from './Main'
export { default as LoginScreen } from './LoginScreen'
export { default as TransferScreen } from './TransferScreen'
export { default as NumberRegisterScreen } from './TransferScreen/NumberRegisterScreen'
export { default as FullNameScreen } from './TransferScreen/FullNameScreen'
export { default as InsertValueScreen } from './TransferScreen/InsertValueScreen'
export { default as ConfirmTransfer } from './TransferScreen/ConfirmTransfer'
export { default as BanksScreen} from './TransferScreen/BanksScreen'
export { default as NumberAgencyScreen} from './TransferScreen/NumberAgencyScreen'
export { default as NumberAccountScreen} from './TransferScreen/NumberAccountScreen'
export { default as DepositScreen } from './DepositScreen'
export { default as PaymentScreen } from './PaymentScreen'
export { default as AccountDetails} from './DepositScreen/AccountDetails'
export { default as ToDeposit} from './DepositScreen/ToDeposit'
export { default as ReceiptPayment} from './PaymentScreen/ReceiptPayment'